BACKUP_IGNORE_HEAD:
- __p
- .
BACKUP_IGNORE_KEY:
- logfile
- logfile_bk
- baselines
BACKUP_IGNORE_TAIL:
- .jpg
- .tar
BASE_PATH: null
LOG_DIR_BACKING_NAME: RAMRLLog
LOG_FOLDER_NAME: logfile
LOG_FOLDER_NAME_BK: logfile_bk
MAIN_MACHINE_IP:
- 127.0.0.1
MAIN_MACHINE_LOG_PATH: /home/luofm/Data/RAMRLLog
MAIN_MACHINE_PASSWD: xxxxxxx
MAIN_MACHINE_PORT:
- 22
MAIN_MACHINE_USER: user_name
WORKSPACE_PATH: /home/luofm/Data
